### ISSUE TITLE
Division by zero during SDLx::Sprite::Animated->new [With proposed solution]

### ISSUE THREAD

**Issue by majorendian** [PerlGameDev/SDL#278]
I am getting the following error message when trying to create a new SDLx::Sprite::Animated object.

```
Use of uninitialized value in division (/) at /usr/local/lib/perl/5.18.2/SDLx/Sprite/Animated.pm line 103.
Illegal division by zero at /usr/local/lib/perl/5.18.2/SDLx/Sprite/Animated.pm line 103.
```

Code to reproduce the issue:

``` perl
use strict;
use warnings;
use SDL;
use SDLx::Sprite::Animated;
use SDL::Image;
use SDL::RWOps;

my $file = "./stop.png";
open my $fh, "<", $file or die $!;
binmode $fh;
local $/ = undef;
my $data = <$fh>;
close $fh;

my $rw = SDL::RWOps->new_const_mem($data);
my $surf = SDL::Image::load_PNG_rw($rw);

my $anim = SDLx::Sprite::Animated->new(
    surface => $surf,
    step_y => 0,
    step_x => 64,
);
```

The image I am using:
stop.png: PNG image data, 128 x 64, 8-bit colormap, non-interlaced
![stop](https://cloud.githubusercontent.com/assets/11798362/7421921/dc19cb12-ef88-11e4-9d8b-256b1e2d8495.png)

I am running a 32bit system with perl 5.18.2

Steps to reproduce:
- Download the image and name it "stop.png"  
- Copy-paste the above code into a main.pl file in the same directory as the image
- Run `perl ./main.pl` from the same directory

You should see the error message mentioned above.

The error function (problematic lines marked with "#<--"):

``` perl
sub _init_default_sequence {
        my $self = shift;

        my $max_x = int( ( $self->surface->w - $_offset_x{ refaddr $self} ) / $self->step_x );  #<--
        my $max_y = int( ( $self->surface->h - $_offset_y{ refaddr $self} ) / $self->step_y );  #<--

        my @sequence;
        foreach my $y ( 0 .. $max_y - 1 ) {
                foreach my $x ( 0 .. $max_x - 1 ) {
                        push @sequence, [ $x, $y ];
                }
        }
        $_sequences{ refaddr $self} = { 'default' => \@sequence };
        $self->sequence('default');
}
```

The object returned by `SDL::Image::Load_PNG_rw($rw)`, is an ordinary `SDL::Surface` and works just fine with `SDLx::Sprite->new(surface => $surf)`

On a related note, the same happens when just doing:

``` perl
use strict;
use warnings;
use SDLx::Sprite::Animated;
my $anim = SDLx::Sprite::Animated->new(image => "stop.png");
```

I have a feeling that I might be missing something. If that is the case, what am I doing wrong?
The error disappears when doing the following:

``` perl
my $anim = SDLx::Sprite::Animated->new(
    image => "stop.png",
    step_x => 1,
    step_y => 1,
);
```

When setting `step_y` or `step_x` to 0 explicitly, it also dies.

After fiddling with this for a while, I managed to find a half-working solution:

``` perl
use strict;
use warnings;

use SDLx::Sprite::Animated;
use SDL;
use SDLx::App;
use SDL::Rect;

my $anim = SDLx::Sprite::Animated->new(
    image => "stop.png",
    step_x => 64,
    step_y => 1,
    rect => SDL::Rect->new(0,0,64,64),
    ticks_per_frame => 6,
    type => "circular",
);
$anim->step_y(0);
$anim->start();

my $app = SDLx::App->new( dt=>0.02, exit_on_quit => 1, w=> 200, h => 200 );
$app->add_show_handler(
    sub{
        my ($step,$app) = @_;
        $app->draw_rect([0,0,$app->w,$app->h],0);
        $anim->draw($app->surface);
        $app->update();
        $app->delay(2);
    }
);

$app->run();

```

But I hit another problem, the `$self->_frame->[1]` in `_update_clip` of the module, for some reason, keeps being incremented. And my Sprite involuntarily leaves the screen. It's Y is being clipped by 1 even though I set `step_y` to 0.

If you need more information just let me know. 
(There seems to be no version information for the module, `cpan -D SDLx::Sprite::Animated` returns 0 for the CPAN field, and `undef` for the "Installed" field)
### Solution

Change:

``` perl
if ($step_y) { #line 136
```

And:

``` perl
if ($step_x) { #line 146
```

To:

``` perl
if(defined $step_y) {
```

And

``` perl
if(defined $step_x) {
```

Respectively, and use the workaround described above.

**Comment by kthakore** [comment]
Awesome thank you! Looking at it. Sorry for the delayed response

**Comment by majorendian** [comment]
No problem, thanks for getting back at me. I already submitted a pull request for this, not sure If you are aware: https://github.com/PerlGameDev/SDL/pull/279  
It also fixes the zero division problem. I hope it's going to be useful here.
